# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pablo/Dropbox/PythonProjects/ImageMosaic/classificador/interface.ui'
#
# Created: Tue Jun  3 12:31:19 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 762)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imagem_original = QtGui.QLabel(self.centralwidget)
        self.imagem_original.setGeometry(QtCore.QRect(20, 20, 331, 251))
        self.imagem_original.setFrameShape(QtGui.QFrame.Box)
        self.imagem_original.setScaledContents(True)
        self.imagem_original.setObjectName("imagem_original")
        self.imagem_classificada = QtGui.QLabel(self.centralwidget)
        self.imagem_classificada.setGeometry(QtCore.QRect(380, 20, 331, 251))
        self.imagem_classificada.setFrameShape(QtGui.QFrame.Box)
        self.imagem_classificada.setScaledContents(True)
        self.imagem_classificada.setObjectName("imagem_classificada")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(550, 560, 62, 27))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 570, 66, 17))
        self.label.setObjectName("label")
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(500, 640, 62, 27))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(570, 640, 62, 27))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(640, 640, 62, 27))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 610, 66, 17))
        self.label_2.setObjectName("label_2")
        self.files_list = QtGui.QListWidget(self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(835, 40, 231, 631))
        self.files_list.setObjectName("files_list")
        self.imagem_exif_list = QtGui.QListView(self.centralwidget)
        self.imagem_exif_list.setGeometry(QtCore.QRect(500, 340, 256, 192))
        self.imagem_exif_list.setObjectName("imagem_exif_list")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(840, 20, 66, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 310, 66, 17))
        self.label_4.setObjectName("label_4")
        self.caminho_pasta_imagens = QtGui.QLineEdit(self.centralwidget)
        self.caminho_pasta_imagens.setGeometry(QtCore.QRect(840, 680, 161, 27))
        self.caminho_pasta_imagens.setObjectName("caminho_pasta_imagens")
        self.botao_pasta_imagens = QtGui.QPushButton(self.centralwidget)
        self.botao_pasta_imagens.setGeometry(QtCore.QRect(1007, 680, 61, 27))
        self.botao_pasta_imagens.setObjectName("botao_pasta_imagens")
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(640, 680, 62, 27))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(570, 680, 62, 27))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(500, 680, 62, 27))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.botao_pasta_imagens, QtCore.SIGNAL("clicked()"), MainWindow.selecionar_pasta)
        QtCore.QObject.connect(self.files_list, QtCore.SIGNAL("itemSelectionChanged()"), MainWindow.selecionar_imagem)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.imagem_original.setText(QtGui.QApplication.translate("MainWindow", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.imagem_classificada.setText(QtGui.QApplication.translate("MainWindow", "Classificada", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Altura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Imagens", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_pasta_imagens.setText(QtGui.QApplication.translate("MainWindow", "Dir", None, QtGui.QApplication.UnicodeUTF8))

